// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/note": {
    params: {};
  };
  "/note/new": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/note" | "/note/new";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/note.tsx": {
    id: "routes/note";
    page: "/note";
  };
  "routes/note-new.tsx": {
    id: "routes/note-new";
    page: "/note/new";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/note": typeof import("./app/routes/note.tsx");
  "routes/note-new": typeof import("./app/routes/note-new.tsx");
};