# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'Notty' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Add the pod for Firebase Cloud Messaging
  pod 'Firebase/Messaging'

end
