name = "nottykv"
main = "src/worker.js"
compatibility_date = "2024-01-31"
workers_dev = true

kv_namespaces = [
  { binding = "nottykv", id = "84b903d3a6b94c82a0aed0d0a30d43e7" }
]

[vars]
SECURITY_KEY = "og44Esu9GE"
