name = "nottykv"
main = "src/worker.ts"
compatibility_date = "2024-01-31"
workers_dev = true

kv_namespaces = [
  { binding = "nottykv", id = "e68c3c76b687441eb2ac6f991e0e2873" }
]

[vars]
SECURITY_KEY = "mIjoGX3Fbl+Mc6ibQccpXw=="
